hacker_news/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from .views import news, comments, jobs


urlpatterns=[
    path('',news, name='news'),
    path('comments/<id>', comments, name='comment'),
    path('jobs/', jobs, name='jobs')
]

hackernews/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hacker_news.urls'))
]

hacker_news/models.py
from django.db import models
import re
import requests

# Create your models here
class Items(models.Model):
    id  = models.IntegerField(primary_key=True,unique=True)
    by = models.CharField(max_length=200, null=True, blank=True)
    type = models.CharField(max_length=200, null=True, blank=True)
    title = models.CharField(max_length=500, null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    descendants = models.IntegerField(null=True, blank=True)
    url = models.CharField(max_length=500, null=True, blank=True)
    deleted = models.BooleanField()
    dead = models.BooleanField()
    created =models.DateTimeField(auto_now_add=True)


class Comments(models.Model):
    id  = models.IntegerField(primary_key=True,unique=True)
    item = models.ForeignKey(Items,null=True, blank=True, on_delete=models.CASCADE)
    by = models.CharField(max_length=200, null=True, blank=True)
    type = models.CharField(max_length=200, null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    parent= models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='+')
    deleted = models.BooleanField()
    created =models.DateTimeField(auto_now_add=True)
    dead = models.BooleanField()

    class Meta:
        ordering = ('created',)

    @property
    def children(self):
        return Comments.objects.filter(parent=self,deleted=False, dead=False)    

hacker_news/views.py
from django.http import HttpRequest
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from .models import Items,Comments
from django.core.paginator import Paginator
import json

def paginator(request,model_items):
    paginator = Paginator(model_items, 25)  # Show 25 contacts per page.

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return page_obj

def news(request):
    items =Items.objects.filter(type='story')
    page_obj = paginator(request,items)
    return render (request,'home.html',{'page_obj':page_obj,'no_pages':page_obj.paginator.page_range})
def comments(request,id):
    item = Items.objects.get(id=id)
    comment = Comments.objects.filter(item=item)
    return render(request, 'comments.html', {'comments':comment,'item':item, 'comment_count':comment.count()})

def jobs(request):
    jobs = Items.objects.filter(type='poll')
    page_obj = paginator(request,jobs)
    return render(request, 'jobs.html',{'page_obj':page_obj,'no_pages':page_obj.paginator.page_range})

def ShowHN(request):
    pass

def AskHN(request):
    pass

hacker_news/templates/Home.html
{% extends 'base.html' %}
{% load static%}
{% block content%}

        <link rel="stylesheet" href="{% static 'css/home.css' %}">
        <ol class="news-list-container">
        <div class="news-lists">
                {% for item in page_obj %}
                <li class="news-item">
                        <p class="news-title"><a href="{{ item.url }}"><i class="fa fa-caret-up" aria-hidden="true"></i>{{item.title}}</a>
                        </p>
                        <a class="news-comment" href="{% url 'comment' item.id %}">
                                <!-- <i class="fa-solid fa-message"></i> -->
                                <i class=" fa-solid fa-message fa-xs"> {{item.comments_set.all.count}}</i>
                        </a>    
                </li>
                
                {% endfor %}
        </div>
</ol>
{% include 'paginator.html'%}

{% endblock %}
    

hacker_news/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    
    <title>Document</title>
</head>
<body>
    <div class="page-body">
        <nav class="nav-container">
            <div class="nav-items-container">
                <ul class="nav-items">
                    <li>Home</li>
                    <li>Stories</li>
                    <li>Ask HN</li>
                    <li>Jobs</li>
                </ul>
            </div>
        </nav>
        {% block content %}{% endblock %}
    </body>
    </div> 
    
</html>

hacker_news/templates/comments.html
{% extends 'base.html' %}
{% block content%}

<div style="overflow: hidden; position:relative;"> 
	<div style="width: 85%; margin: 50px auto; ">
		<h2>{{item.title}}</h2>
		{% for comment in comments%}
			{%if not comment.parent%}
			<div style="width: 80%; margin-bottom: 20px;">
				<h3 style="color: rgb(74, 75, 75);"> by :{{comment.by}}</h3>
				<p>{{comment.text|safe}}</p>
			</div>
			{%endif%}
			{% for child in comment.children%}
				<div style="color: rgb(31, 171, 171); width: 60%; padding-left: 30px; margin-bottom: 20px;">
					<h3>by : {{child.by}}</h3>
					<p>{{child.text|safe}}</p>
				</div>
				{% endfor%}
		{% endfor%}
	</div>
</div>
{% endblock %}

hacker_news/templates/jobs.html
{% extends 'base.html' %}
{% load static%}
{% block content%}

        <link rel="stylesheet" href="{% static 'css/home.css' %}">
        <ol class="news-list-container">
                <div class="news-lists">
                        {% for job in page_obj %}
                        <li class="news-item">
                                <p class="news-title"><a href="{{ job.url }}"><i class="fa fa-caret-up" aria-hidden="true"></i>{{job.title}}</a>
                                </p>

                        </li>
                        {% endfor %}
                </div>
        </ol>
        {% include 'paginator.html'%}

{% endblock %}

hacker_news/templates/paginator.html
<div class="pagination">
    <span class="step-links">
        <!-- {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %} -->

        <!-- <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span> -->

        {% if page_obj.has_next %}
            {% for num in no_pages %}
                <a href="?page={{num}}">{{num}}</a>
            {%endfor%}
        {% endif %}
    </span>
</div>